.catalog:
  name: 01-simpleNodeApp
  version: d01
  description:
  uuid: 01-simpleNodeApp-1
  minimum_rancher_version: 1.6
  questions:
    - variable: "host_group"
      description:
      label: "Host Group:"
      required: true
      default: 'simplenodeapp'
      type: "string"
version: '3.3'
services:
  customer-node-app:
    scale: 1
    start_on_create: true
    health_check:
      healthy_threshold: 2
      response_timeout: 2000
      port: 42
      unhealthy_threshold: 3
      initializing_timeout: 60000
      interval: 2000
      strategy: recreate
      reinitializing_timeout: 60000